### ISSUE TITLE
link to the pretrained_weights is not available

### ISSUE THREAD

**Issue by Kirillova-Anastasia** [TXH-mercury/VALOR#1]
Hi!
Thanks for your great job!

The link to the "pretrained_weights" (first in the section "Download Checkpoints") is not available. It gives me "You need access"

**Comment by Kirillova-Anastasia** [comment]
The same for this link: https://drive.google.com/file/d/1pWym3bMNW_WrOZCi5Ls-wKFpaPMbLOio/view?usp=sharing

**Comment by johncaged** [comment]
We have already fixed the problem. If you have any other questions, please feel free to contact us.
