### ISSUE TITLE
"Output file #0 does not contain any stream"

### ISSUE THREAD

**Issue by zsw111-zzz** [TXH-mercury/VALOR#10]
Thank you for your excellent contribution, but I found some problems when running the code: When I processed the MSRVTT dataset through extract_frame_and_wav_multiprocess.py, when processing some videos, an error "Output file #0 does not contain any stream" appeared, In the end, all the pictures were successfully extracted for the MSRVTT dataset, but only 8811 audio files were extracted. Is this normal, maybe because some videos in the MSRVTT dataset have no audio? Looking forward to your response, thank you again for your contribution to the field of video retrieval!

**Comment by TXH-mercury** [comment]
Hi @zsw111-zzz , Yes, there other videos in MSRVTT dataset dosenot contain audios. In this scenario the audio mapper in data loader will simply return a full-zero tensor and foward into tri-modality training, which we emprically found better than the other solution that separately feed videos with audio tracks into tri-modality training and those w/o audios into dual-modality training.

**Comment by zsw111-zzz** [comment]
Thank you very much for your reply. Once again, I applaud for your outstanding contribution!
