### ISSUE TITLE
Inference code

### ISSUE THREAD

**Issue by abhimanyu891998** [TXH-mercury/VALOR#19]
Hi, would it be possible to release a demo or code through which I could essentially perform inference on a video. I would like to get embeddings (MGA) for video clips, text and background audio in the same latent space.

**Comment by fazliimam** [comment]
+1

**Comment by aTunass** [comment]
+2

**Comment by poppynull** [comment]
+3

**Comment by shiztong** [comment]
+4

**Comment by dragen1860** [comment]
i guess someone must have implement it themselves. kindly share it then?

**Comment by TXH-mercury** [comment]
A simple Inference code is added
