### ISSUE TITLE
Providing all versions of pretrained weights

### ISSUE THREAD

**Issue by YingtianDt** [TXH-mercury/VALOR#21]
Hi, could you also provide all versions of the pretrained weights for BERT,CLIP,VideoSwin? And could you explain how different version of these backbone corresponds to the version of the VALOR weights? Thanks!

**Comment by TXH-mercury** [comment]
pretrained weights for BERT,CLIP,VideoSwin are already provided. VALOR-base use videoswin and bert. VALOR-large use CLIP and bert
