### ISSUE TITLE
Here guessing what to do to start runbning this on videos

### ISSUE THREAD

**Issue by spacewalkingninja** [TXH-mercury/VALOR#4]
Hey guys! I got to installing it, apex finally installed, and all is here. Models downloaded.
How do I run the inference on videos? I already extracted the video and audio and now what should I run, train or test?

**Comment by TXH-mercury** [comment]
Hi ninja, Sorry for the absence of inference code (I am too busy recently). I suggest that wrap the dataset and that run test.

**Comment by spacewalkingninja** [comment]
Will try again later, I got to somewhere yesterday or the other day, I dont remember. Been busy too, working on ais and full time, almost 16 hours a day. Thx for support and not being like the ones that dont release models, i appreciate all models released as my 1070 8gb and measely 36ram wont be able to train anything like that hahaha. Actually I almost got ur thing to do something but it was crashing... Will try later and write back 
love peaceout

**Comment by tensorboy** [comment]
@spacewalkingninja did you managed to run inference?

**Comment by kenhuang1964** [comment]
@spacewalkingninja I'm wondering the same thing. Did you manage to run inference?

**Comment by lzyuan168** [comment]
Hi @spacewalkingninja would you be able to share how did you do the inference code. Thank you

**Comment by TXH-mercury** [comment]
Inference code is added
