### ISSUE TITLE
Errors in loading Bert and attention score calculation

### ISSUE THREAD

**Issue by Kirillova-Anastasia** [TXH-mercury/VALOR#5]
Hi, thanks for your interesting work!

I'm trying to reproduce your results. Running 'sh preinstall.sh' I get some errors with Bert model. 
I downloaded pretrained weights from your link from "Download Checkpoints" section. I use "pretrained_weights/bert_base_uncased_config.json" and "pretrained_weights/bert-base-uncased.bin" files.
However
1) I have some unexpected_keys in multimodal encoder and a lot of missing keys, while loading state_dict. Is it okay?
2) I got the following error in cross attention calculation:
```
File "/VALOR/model/bert.py", line 334, in forward
    attention_scores = torch.matmul(query_layer, key_layer.transpose(-1, -2))
RuntimeError: The size of tensor a (5000) must match the size of tensor b (250) at non-singleton dimension 0
```
Size of query_layer tensor is [5000, 12, 42, 64], size of key_layer tensor is [250, 12, 49, 64]

**Comment by TXH-mercury** [comment]
> Hi, thanks for your interesting work!
> 
> I'm trying to reproduce your results. Running 'sh preinstall.sh' I get some errors with Bert model. I downloaded pretrained weights from your link from "Download Checkpoints" section. I use "pretrained_weights/bert_base_uncased_config.json" and "pretrained_weights/bert-base-uncased.bin" files. However
> 
> 1. I have some unexpected_keys in multimodal encoder and a lot of missing keys, while loading state_dict. Is it okay?
> 2. I got the following error in cross attention calculation:
> 
> ```
> File "/VALOR/model/bert.py", line 334, in forward
>     attention_scores = torch.matmul(query_layer, key_layer.transpose(-1, -2))
> RuntimeError: The size of tensor a (5000) must match the size of tensor b (250) at non-singleton dimension 0
> ```
> 
> Size of query_layer tensor is [5000, 12, 42, 64], size of key_layer tensor is [250, 12, 49, 64]

Hi, Kirillova:
1) it's normal, the unexpected keys in multimodal encoder are the prediction heads, which we load in our heads initial part. 
The missing keys are the additional cross attention layer which does not exist in the vanilla BERT model and have to be randomly initialized. 
2) It seems that the batch size dim is doesnot match. I suggest check the batch sizes of tokenized input and conditional feats input.
