### ISSUE TITLE
About prerequisite

### ISSUE THREAD

**Issue by isjwdu** [TXH-mercury/VALOR#6]
Thanks for your very good work. Excellent performance on my audio-text multimodal dataset. 
I'd like to ask if there are any plans to streamline or optimize the NVIDIA/Apex related content in the future, I got tons of weird bugs when setting up my environment and I believe this will also cause problems for others who want to try your repo.

**Comment by TXH-mercury** [comment]
hi @isjwdu  ,  I have tried again and indeed meet bugs when installing apex, i guess it comes from the newest apex version. So I add an relatively old version apex to our repo and directly build this apex works well. Thank you  for the great advice.
