### ISSUE TITLE
Inference Code

### ISSUE THREAD

**Issue by isjwdu** [TXH-mercury/VALOR#7]
Hi. Do you have any plans to release the inference code?

**Comment by TXH-mercury** [comment]
Hi @isjwdu , Sorry that I haven't wrote inference code yet and am too busy at this period. It may become the TODO after serveral months, and you could write by yourself according to test code.

**Comment by isjwdu** [comment]
Thank you for your reply, I have written code for the tasks I need.

> Hi @isjwdu , Sorry that I haven't wrote inference code yet and am too busy at this period. It may become the TODO after serveral months, and you could write by yourself according to test code.

**Comment by lzyuan168** [comment]
Hi @isjwdu may I know if you have written the inference code and could you share how its done. Thank you

**Comment by fazliimam** [comment]
Hi @isjwdu I would appreciate if you could share the inference code

**Comment by poppynull** [comment]
Hi @isjwdu may I know if you have written the inference code and could you share how its done. Thank you！！！

**Comment by dragen1860** [comment]
anyone share the infereonce demo code?

**Comment by Dewmi24** [comment]
please share an inference code
