### ISSUE TITLE
Some videos in VALOR-32K are unavailable on YouTube

### ISSUE THREAD

**Issue by ttgeng233** [TXH-mercury/VALOR#8]
Thank you so much for your excellent work!

I found many videos in the proposed VALOR-32K are unavailable on YouTube. 146 and 151 videos in the test and val sets are unavailable, respectively. And I am still downloading videos in the train set.  
Can you provide the original raw videos for these unavailable ones for me? Because it is a large number of videos that can definitely affect the model's performance.

**Comment by TXH-mercury** [comment]
Hi @ttgeng233 , thanks for attention, sorry that I can't direcly share videos here, please email to sihan.chen@nlpr.ia.ac.cn.

**Comment by pribadihcr** [comment]
> Thank you so much for your excellent work!
> 
> I found many videos in the proposed VALOR-32K are unavailable on YouTube. 146 and 151 videos in the test and val sets are unavailable, respectively. And I am still downloading videos in the train set. Can you provide the original raw videos for these unavailable ones for me? Because it is a large number of videos that can definitely affect the model's performance.

Hi @ttgeng233 do you have a script to download the dataset?
Thanks

**Comment by TXH-mercury** [comment]
> > Thank you so much for your excellent work!
> > I found many videos in the proposed VALOR-32K are unavailable on YouTube. 146 and 151 videos in the test and val sets are unavailable, respectively. And I am still downloading videos in the train set. Can you provide the original raw videos for these unavailable ones for me? Because it is a large number of videos that can definitely affect the model's performance.
> 
> Hi @ttgeng233 do you have a script to download the dataset? Thanks

@pribadihcr please leave your email and I will send videos.

**Comment by BingliangLi** [comment]
Hi, thanks for opensource your dataset, I'm also very interested in VALOR-32K, could you please send me the links to the videos? Thanks! My email is bingliangli@link.cuhk.edu.cn
